export { createGqlFetch, type GqlFetch } from './client';
export { useMe, type Me, type UseMeParams } from './hooks/useMe';
export { useUpdateMe, type UpdateMeInput, type UseUpdateMeParams } from './hooks/useUpdateMe';
export { useSchools, type School, type UseSchoolsParams } from './hooks/useSchools';
export { useStartRound, type PollRound, type RoundPoll, type RoundChoice, type UseStartRoundParams } from './hooks/useStartRound';
export { useVote, type VoteInput, type UseVoteParams } from './hooks/useVote';
export { useCompleteRound, type UseCompleteRoundParams } from './hooks/useCompleteRound';
export { useFlames, type Flame, type FlamesResult, type UseFlamesParams } from './hooks/useFlames';
export { useMarkFlamesRead, type UseMarkFlamesReadParams } from './hooks/useMarkFlamesRead';
export { useNotifications, type Notification, type UseNotificationsParams } from './hooks/useNotifications';
export { useMarkNotificationsRead, type UseMarkNotificationsReadParams } from './hooks/useMarkNotificationsRead';
export { useRevealFlame, type UseRevealFlameParams } from './hooks/useRevealFlame';
export { useRevealFlameName, type UseRevealFlameNameParams } from './hooks/useRevealFlameName';
export { useActivateGodMode, type UseActivateGodModeParams } from './hooks/useActivateGodMode';
